---
title: "Road Maps of Hawaii"
date: "`r Sys.Date()`"
output:
  data: "hawaii"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               widgetframe_widgetsdir = 'widgets')
opts_knit$set(width=75)
```

I would check out this repo and run through it to get more ideas!
https://github.com/jkaupp/tidytuesdays/blob/master/2019/week40/R/analysis.R 

## Making Road Network Maps

Add custom themes and functions

```{r}
# source theme for roads
source("../R/road-theme.R")
```

```{r}
library(sf)
library(foreign)
library(tidyverse)
library(lwgeom)

options(stringsAsFactors = FALSE)

cities_geolocation <- read_csv("../data/cities_geolocation.csv")

files <- list.files(path = "../data/shapefiles/road-network/featnames", pattern="*.dbf", full.names=TRUE, recursive=FALSE) %>% as.data.frame
names(files) <- c("path")
files$GEOID <- substr(files$path, 21, 25)

road_files <- list.files(path = "../data/shapefiles/road-network/roads/", pattern="*.shp$", full.names=TRUE, recursive=FALSE) %>% as.data.frame
names(road_files) <- c("path")

allroads <-NULL

#----------combine em all and add suffixes--------------
for (i in 1:nrow(files)) {
  #read in the feature names file, which has road suffixes in it
  featname <- read.dbf(files$path[i],  as.is = TRUE)
  featname$SUFTYPABRV[is.na(featname$SUFTYPABRV)] <- featname$PRETYPABRV[is.na(featname$SUFTYPABRV)]
  featname <- featname %>% dplyr::select(LINEARID, SUFTYPABRV) %>% unique

  #read in the roads shapefile as a simple features dataframe
roads <- read_sf(road_files$path[i]) 
roads$len <- st_length(roads)
  #join the two 
  temp <- inner_join(roads, featname, by = "LINEARID") 
  
  #merge em all
  if (i==1) {
    allroads <- temp
  }else {
    allroads <- do.call(rbind, list(temp, allroads))
  }
}

saveRDS(allroads, "data/roadNetwork-basemaps/rds/hawaii-allRoads.rds")
```

Make the first plot

```{r}

for (j in 1:nrow(cities_geolocation)){
allroads <- readRDS("../data/shapefiles/road-network/roadNetwork-basemaps/rds/hawaii-allRoads.rds")
pt <- data.frame(lat = cities_geolocation$lat[j], long = cities_geolocation$lon[j])

pt <- pt %>% st_as_sf(coords = c("long", "lat"), crs = 4326) %>% st_transform(2163)
circle <- st_buffer(pt, dist = 24140.2)
circle <- circle %>% st_transform(st_crs(temp))
allroads <- st_intersection(circle, allroads)

#-----------figure out plot colors automagically------
plottype <- allroads %>% select(SUFTYPABRV,len) 
plottype$geometry <- NULL
plottype <- subset(plottype, !is.na(SUFTYPABRV))
plottype <- plottype %>% group_by(SUFTYPABRV) %>% summarise(Length = sum(len)) %>% arrange(-Length) %>% head(8)

#these ones I want to set always
plotcolors <- c('Other' = '#cccccc')

#get what's leftover
findcolors <- plottype$SUFTYPABRV
colors <- c('#59c8e5', '#fed032',  '#4cb580', '#fe9ea5', '#fe4d64', '#0a7abf', '#ff9223', '#2e968c')

if(length(findcolors[findcolors=="Ave"])>0) {
  plotcolors <- c(plotcolors, "Ave" = '#59c8e5')
  findcolors <- findcolors[findcolors !="Ave"]
  colors <- colors[colors !="#59c8e5"]
}

if(length(findcolors[findcolors=="St"])>0) {
  plotcolors <- c(plotcolors, "St" = '#fed032')
  findcolors <- findcolors[findcolors !="St"]
  colors <- colors[colors !="#fed032"]
}

if(length(findcolors[findcolors=="Rd"])>0) {
  plotcolors <- c(plotcolors, "Rd" = '#4cb580')
  findcolors <- findcolors[findcolors !="Rd"]
  colors <- colors[colors !="#4cb580"]
}


if(length(findcolors[findcolors=="I-"])>0) {
  plotcolors <- c(plotcolors, "I-" = '#fe4d64')
  findcolors <- findcolors[findcolors !="I-"]
  colors <- colors[colors !="#fe4d64"]
}

if(length(findcolors[findcolors=="Dr"])>0) {
  plotcolors <- c(plotcolors, "Dr" = '#0a7abf')
  findcolors <- findcolors[findcolors !="Dr"]
  colors <- colors[colors !="#0a7abf"]
}

if(length(findcolors[findcolors=="Blvd"])>0) {
  plotcolors <- c(plotcolors, "Blvd" = '#2e968c')
  findcolors <- findcolors[findcolors !="Blvd"]
  colors <- colors[colors !="#2e968c"]
}

if(length(findcolors[findcolors=="US Hwy"])>0) {
  plotcolors <- c(plotcolors, "US Hwy" = '#ff9223')
  findcolors <- findcolors[findcolors !="US Hwy"]
  colors <- colors[colors !="#ff9223"]
}

if(length(findcolors[findcolors=="State Hwy"])>0 &length(colors[colors=="#ff9223"])>0) {
  plotcolors <- c(plotcolors, "State Hwy" = '#ff9223')
  findcolors <- findcolors[findcolors !="State Hwy"]
  colors <- colors[colors !="#ff9223"]
}

if(length(findcolors[findcolors=="Hwy"])> 0 & length(colors[colors=="#ff9223"])>0) {
  plotcolors <- c(plotcolors, "Hwy" = '#ff9223')
  findcolors <- findcolors[findcolors !="Hwy"]
  colors <- colors[colors !="#ff9223"]
}


#go thru and assign the rest in order
for (i in 1:length(colors)) {
  tempnames <- names(plotcolors)
  plotcolors <- c(plotcolors, colors[i]) 
  names(plotcolors) <- c(tempnames, findcolors[i])
}


#-----------plot----------
suff <- plottype$SUFTYPABRV
allroads$SUFTYPABRV[!(allroads$SUFTYPABRV %in% suff)] <- "Other"

otherroads <- allroads[(allroads$SUFTYPABRV  == "Other"),]
allroads <- allroads[(allroads$SUFTYPABRV  != "Other"),]

p1 <- ggplot() + 
  geom_sf(key_glyph = draw_key_point, 
          data=otherroads, size = .45, aes(color=SUFTYPABRV)) + 
  geom_sf(key_glyph = draw_key_point, data=allroads, size = .55, aes(color=SUFTYPABRV)) + 
  
  scale_color_manual(values = plotcolors, guide = "legend") + theme_map() +
  labs(title = paste0(cities_geolocation$city[j])) + labs(color='') +
  guides(color = guide_legend(override.aes = list(size = 4)))

saveRDS(p1, paste0("../data/roadNetwork-basemaps/rds/", cities_geolocation$city[j], "-roadNetwork.rds"))
ggsave(paste0("../data/roadNetwork-basemaps/figs/", cities_geolocation$city[j], "-roads.png"))
}
```

