---
title: "Fix projection coordinates"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library(dplyr)
```

# Fix coordinate mis-match

The raw raster and vector data have different projections which need to be corrected.
We will also subset the raster reliefs to reduce their size for quicker loading in `Shiny`.

## Subset rasters

```{r}
# function to subset raster
subset_raster <- function(filename = filename, depth = depth){
  prefix <- gsub(".tif", "", filename)
raster_data = raster::raster(paste0(here::here("data/relief"), "/", depth, "/", filename))
hawaii_relief <- raster_data %>%
        as("SpatialPixelsDataFrame") %>%
        as.data.frame() %>%
        dplyr::rename(., value = prefix) %>%
        dplyr::filter(value != 255)
hawaii_relief$y = hawaii_relief$y - 1104600
data.table::fwrite(hawaii_relief,
                   paste0(here::here("data/relief"), "/", depth, "/", prefix, ".csv"))
}

# state of hawaii
subset_raster(filename = "srgrhii0100a.tif", depth = "100m")
subset_raster(filename = "srgyhii200a.tif", depth = "200m")
# island of hawaii
subset_raster(filename = "hawaii_100m.tif", depth = "100m")
subset_raster(filename = "hawaii_200m.tif", depth = "200m")
# island of maui
subset_raster(filename = "maui_100m.tif", depth = "100m")
subset_raster(filename = "maui_200m.tif", depth = "200m")
# island of oahu
subset_raster(filename = "oahu_100m.tif", depth = "100m")
subset_raster(filename = "oahu_200m.tif", depth = "200m")
# islands of oahu, molokai, & maui
subset_raster(filename = "oahu_molokai_maui_100m.tif", depth = "100m")
subset_raster(filename = "oahu_molokai_maui_200m.tif", depth = "200m")
# island of kauai
subset_raster(filename = "kauai_100m.tif", depth = "100m")
subset_raster(filename = "kauai_extended_100m.tif", depth = "100m")
subset_raster(filename = "kauai_200m.tif", depth = "200m")
subset_raster(filename = "kauai_extended_200m.tif", depth = "200m")
```

## Correct shapefiles 

```{r}
raster_data = raster::raster(here::here("data/relief/100m", "srgrhii0100a.tif"))
hawaii_relief <- raster_data %>%
        as("SpatialPixelsDataFrame") %>%
        as.data.frame() %>%
        dplyr::rename(., value = "srgrhii0100a") %>%
        dplyr::filter(value != 255)
hawaii_relief$y = hawaii_relief$y - 1104000
coast_data <- read_sf(here::here("data/shapefiles/coastline", "Coastline.shp"))
# The raster and vector datasets should have the same projection but they do not:
raster_projection = projection(raster_data)
vector_projection = st_crs(coast_data)$proj4string

shapefiles <- list.files(pattern = "\\.shp$", recursive = TRUE)
for(i in 1:length(shapefiles)){
  data <- read_sf(shapefiles[i])
  file_name <- sub('.*\\/', '', shapefiles[i])
  geo <- data %>% 
    st_transform(raster_projection)
  sf::write_sf(geo, paste0(here::here("data/shapefiles/corrected_projections"), "/", file_name))
}
```